apiVersion: v2
name: camunda-custom
description: Custom Camunda 8 deployment wrapper
type: application
version: 1.0.0
appVersion: "8.4"

dependencies:
  - name: camunda-platform
    version: "10.0.2"  # Proveri najnoviju verziju
    repository: https://helm.camunda.io